package hardcore_checkpoints.server.state;

public enum CheckpointPhase {
	BOOTSTRAP,
	INCOMPLETE_CONTROL_DATA,
	FEATURE_DISABLED,
	ENABLING_NEW_CYCLE,
	WAITING_FOR_ROSTER,
	ADMISSION_FROZEN,
	WAITING_FOR_PLAYERS,
	SYNCING,
	CREATING_INITIAL_CHECKPOINT,
	INITIAL_CHECKPOINT_FAILED,
	START_COUNTDOWN,
	RUNNING,
	PAUSING,
	PAUSED,
	QUIESCING,
	SAVING,
	RESTORING_CONSUMED_RECORDERS,
	DEATH_COUNTDOWN,
	ROLLBACK_PENDING,
	RESTORING,
	RECOVERY_FAILED,
	DISABLING_FOR_RESTART,
	DISABLE_RESTART_FAILED;

	public boolean isGameplayFrozen() {
		return this != FEATURE_DISABLED && this != RUNNING && this != DEATH_COUNTDOWN;
	}

	public boolean isDeathRecovery() {
		return this == DEATH_COUNTDOWN || this == ROLLBACK_PENDING || this == RESTORING || this == RECOVERY_FAILED;
	}

	public boolean locksRosterMutations() {
		return switch (this) {
			case ENABLING_NEW_CYCLE, CREATING_INITIAL_CHECKPOINT, QUIESCING, SAVING,
					RESTORING_CONSUMED_RECORDERS, ROLLBACK_PENDING, RESTORING, RECOVERY_FAILED,
					DISABLING_FOR_RESTART -> true;
			default -> false;
		};
	}
}
