package hardcore_checkpoints.server.network;

public enum ControlAction {
	PREPARE,
	WITHDRAW_READY,
	RETURN_TO_WAITING,
	SUBMIT_JOIN_REQUEST,
	WITHDRAW_JOIN_REQUEST,
	APPROVE_JOIN_REQUEST,
	REJECT_JOIN_REQUEST,
	MARK_PENDING_ADDITION,
	CANCEL_PENDING_ADDITION,
	REMOVE_ROSTER_MEMBER,
	REFRESH_STATE
}
